stages:
  - build

build:sh4-gcc:
  stage: build
  image: haydenkow/nu_dckos
  script:
    - source /etc/bash.bashrc
    - make clean build link
    - tar -zcf gldc.tar.gz libGLdc.a LICENSE README.md include
  artifacts:
    paths:
    - gldc.tar.gz
