stages:
  - build
  - test

build:sh4-gcc:
  stage: build
  image: kazade/dreamcast-sdk
  script:
    - source /etc/bash.bashrc
    - mkdir builddir
    - cd builddir
    - cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/Dreamcast.cmake -DCMAKE_BUILD_TYPE=Release ..
    - make
    - tar -zcf gldc.tar.gz libGL.a ../LICENSE ../README.md ../include
  artifacts:
    paths:
    - builddir/gldc.tar.gz

build:x86-gcc:
  stage: build
  image: fedora:38
  before_script:
    - sudo dnf install -y cmake gcc gcc-c++ SDL2.i686 SDL2-devel.x86_64 glibc-devel glibc-devel.i686 SDL2-devel.i686 pkgconf-pkg-config.i686 pkgconf-pkg-config.x86_64
  script:
    - mkdir builddir
    - cd builddir
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make
  artifacts:
    paths:
    - builddir/tests/gldc_tests

test:x86-gcc:
  stage: test
  image: fedora:38
  dependencies:
    - build:x86-gcc
  before_script:
    - sudo dnf install -y cmake gcc gcc-c++ SDL2.i686 SDL2-devel glibc-devel pkgconf-pkg-config glibc-devel.i686 SDL2-devel.i686 pkgconf-pkg-config.i686
  script:
    - cd builddir/tests/
    - SDL_VIDEODRIVER=dummy ./gldc_tests --junit-xml=report.xml
  artifacts:
   reports:
    junit: builddir/tests/report.xml
